### ISSUE TITLE
Delivery entity重构成DeliveryForStore和DeliveryForPlant

### ISSUE THREAD

**Issue by devarchi33** [hublabs/delivery-api#10]

**Comment by jaehue** [comment]
@devarchi33 이슈명에 두레이 링크는 제거하는게 나을 것 같아요.
이 프로젝트는 오픈소스로 누구나 참여할 수 있는데(물론 지금은 우리만 하고 있지만)
접근 불가능한 두레이 링크가 이슈 제목에 들어가는 것은 오픈 소스 프로젝트에 맞지 않는 것 같습니다.
